### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by palaparthi** [ttjordan/team-management-instawork#1]
Hi,

Could you please update the setup instructions? below is the issue I am facing during setup.

<img width="824" alt="Screenshot 2024-10-30 at 10 29 44 PM" src="https://github.com/user-attachments/assets/c166d56d-fc29-4ca6-98b6-e3df7bd65882">

**Comment by ttjordan** [comment]
@palaparthi I think the error is due to the fact that the virtual environment was not set up. 
I have edited the readme to include the prerequisites set up instructions. More details are in the linked article in that section that explains how it works. 
Let me know if it is more clear now!

**Comment by palaparthi** [comment]
Thanks, I think the project is missing the requirements.txt file, can you please add it?

**Comment by ttjordan** [comment]
@palaparthi added the requirements.txt file.
